version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgresToDo
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjsToDo
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PORTAINER_CONTAINER_ID: ${PORTAINER_CONTAINER_ID}
      PORTAINER_SECRET: ${PORTAINER_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - minio
    restart: always
    command: sh -c "until nc -z minio 9000; do echo 'Waiting for Minio...'; sleep 2; done; npm run start:dev"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminToDo
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minioToDo
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
  minio-data:
