FROM node:20-bullseye

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g ts-node nodemon

COPY . .

EXPOSE 3000

CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts", "--exec", "ts-node src/main.ts", "--legacy-watch", "--polling"]