version: "3.3"

services:
  postgres:
    image: postgres:13
    container_name: postgresToDo
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjsToDo
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432/todo
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminToDo
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
