FROM node:20-bullseye

RUN apt-get update && apt-get install -y netcat

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install -g ts-node nodemon

COPY . .

EXPOSE 3000

CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "--ext", "ts", "--exec", "ts-node src/main.ts"]