services:
  postgres:
    image: postgres:13
    container_name: postgresToDo
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjsToDo
    ports:
      - "3000:3000"
    env_file:
      - ./stack.env
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    pull_policy: build
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminToDo
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: